//! Codegen: typed live handles from the shared contract asset.
//!
//! For every template whose contract declares `live` fields (the data keys
//! Python exposes a property setter for — derived, so it can't drift), emit a
//! `{Kind}Handle` with typed getters/setters: `SliderHandle::set_max(f64)`,
//! `TableHandle::set_selected(&[i64])`, … A typo'd or register-time-only
//! field is a compile error instead of a silently ignored update.
//!
//! Output: `$OUT_DIR/live_handles.rs`, `include!`d at the bottom of lib.rs.

use std::{env, fs, path::Path};

/// Contract type string -> (param type, json! conversion, getter return, extractor).
fn map_type(t: &str) -> (&'static str, &'static str, &'static str, &'static str) {
    let base = t.split(&['|', ' '][..]).next().unwrap_or(t);
    match base {
        "number" => ("f64", "json!(v)", "f64", ".and_then(|v| v.as_f64())"),
        "bool" => ("bool", "json!(v)", "bool", ".and_then(|v| v.as_bool())"),
        "str" => ("&str", "json!(v)", "String",
                  ".and_then(|v| v.as_str().map(String::from))"),
        "list[int]" => ("&[i64]", "json!(v)", "Vec<i64>",
                        ".and_then(|v| serde_json::from_value(v).ok())"),
        "list[str]" => ("&[&str]", "json!(v)", "Vec<String>",
                        ".and_then(|v| serde_json::from_value(v).ok())"),
        _ => ("Value", "v", "Value", ""),
    }
}

fn pascal(kind: &str) -> String {
    kind.split('_')
        .map(|w| {
            let mut c = w.chars();
            match c.next() {
                Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn main() {
    let asset = "../danvas/templates/components.json";
    println!("cargo:rerun-if-changed={asset}");
    let json: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(asset).expect("templates asset"))
            .expect("valid components.json");
    let templates = json["templates"].as_object().expect("templates map");

    let mut out = String::from(
        "// @generated by build.rs from danvas/templates/components.json — do not edit.\n\n");
    let mut kinds: Vec<&String> = templates.keys().collect();
    kinds.sort();
    for kind in kinds {
        let tpl = &templates[kind.as_str()];
        let live: Vec<&str> = tpl["contract"]["live"]
            .as_array().map(|a| a.iter().filter_map(|v| v.as_str()).collect())
            .unwrap_or_default();
        if live.is_empty() {
            continue;
        }
        let name = format!("{}Handle", pascal(kind));
        out += &format!(
            "/// Typed live handle for a `{kind}` panel — getters/setters for its\n\
             /// contract's `live` fields. From [`Client::{kind}_handle`].\n\
             pub struct {name}<'a> {{ client: &'a Client, id: String }}\n\
             impl<'a> {name}<'a> {{\n");
        for field in &live {
            let ty = tpl["contract"]["data"][field].as_str().unwrap_or("");
            let (param, conv, ret, extract) = map_type(ty);
            out += &format!(
                "    /// Write `{field}` live (contract: `{ty}`).\n\
                 \x20   pub fn set_{field}(&self, v: {param}) {{\n\
                 \x20       self.client.live_set(&self.id, \"{field}\", {conv});\n\
                 \x20   }}\n\
                 \x20   /// Read `{field}` — registered data merged with everything streamed since.\n\
                 \x20   pub fn {field}(&self) -> Option<{ret}> {{\n\
                 \x20       self.client.live_get(&self.id, \"{field}\"){extract}\n\
                 \x20   }}\n");
        }
        out += "}\n";
        out += &format!(
            "impl Client {{\n\
             \x20   /// The typed live handle for a `{kind}` panel (own or a peer's;\n\
             \x20   /// peer writes route via set_props to the owner's real setters).\n\
             \x20   pub fn {kind}_handle(&self, id: &str) -> {name}<'_> {{\n\
             \x20       {name} {{ client: self, id: id.into() }}\n\
             \x20   }}\n\
             }}\n\n");
    }
    fs::write(Path::new(&env::var("OUT_DIR").unwrap()).join("live_handles.rs"), out)
        .expect("write live_handles.rs");
}
