"""Render the canonical wire protocol to a frontend JS module.

Single source of truth lives in :mod:`pycanvas._protocol`; this script emits
``pycanvas/frontend/src/protocol.generated.js`` from it so the browser code
imports the same binary codes, flag wire keys, and message-type tags instead of
re-declaring them. Run it whenever ``_protocol.py`` changes:

    python scripts/gen_protocol.py

``tests/test_protocol_sync.py`` regenerates into memory and fails if the
committed file is stale, so CI catches a forgotten run.
"""

from __future__ import annotations

import json
import os
import sys

# Import the package from the repo root regardless of where this is run from.
_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from pycanvas import _protocol  # noqa: E402

OUT_PATH = os.path.join(
    _ROOT, "pycanvas", "frontend", "src", "protocol.generated.js"
)

_HEADER = (
    "// AUTOGENERATED by scripts/gen_protocol.py from pycanvas/_protocol.py.\n"
    "// Do not edit by hand — change _protocol.py and re-run the generator.\n"
    "// The Python <-> browser wire contract (binary codes, lock-flag wire\n"
    "// keys, JSON frame type tags) lives in one place so the two sides can't\n"
    "// drift; tests/test_protocol_sync.py fails if this file is stale.\n"
)


def render():
    """Return the JS module text for the current protocol definition."""
    p = _protocol.as_dict()
    lines = [_HEADER]
    # Binary frame codes -> `export const BIN_VIDEO = 1` etc.
    for name, code in p["binary_frame_codes"].items():
        lines.append(f"export const BIN_{name} = {code}")
    lines.append("")
    # Flag wire keys -> a frozen object keyed by Python flag name.
    lines.append("export const FLAG_WIRE_KEYS = Object.freeze("
                 + json.dumps(p["flag_wire_keys"]) + ")")
    lines.append("")
    # Message-type tags -> frozen arrays for reference / validation.
    lines.append("export const MESSAGE_TYPES_OUT = Object.freeze("
                 + json.dumps(p["message_types_out"]) + ")")
    lines.append("export const MESSAGE_TYPES_IN = Object.freeze("
                 + json.dumps(p["message_types_in"]) + ")")
    lines.append("")
    return "\n".join(lines)


def main():
    text = render()
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
