"""Generate examples/README.md — an index of every example, grouped by topic,
from each script's module docstring (first line = the summary).

    python scripts/gen_examples_index.py        # (also run by gen_all.py)

Grouping is by filename in GROUPS below; anything unlisted lands in "More".
A script with no docstring is reported and listed with a blank summary, so
the gap is visible rather than silent.
"""
import ast
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EX = os.path.join(ROOT, "examples")
OUT = os.path.join(EX, "README.md")

GROUPS = [
    ("Start here", ["hello_world", "readme_tour", "frontend_backend_tour",
                    "architecture", "catalogue", "show_anything"]),
    ("Input, output and handlers", ["action_routing", "readback_and_save",
                                    "dispatch_trace_demo", "download_button",
                                    "upload_button", "file_endpoints",
                                    "file_browser", "file_tree"]),
    ("Custom and React panels", ["custom_html", "custom_component",
                                 "custom_binary_stream", "custom_styled_component",
                                 "react_component", "react_request",
                                 "react_canvas_api", "react_styled_component",
                                 "shared_components", "analog_clock",
                                 "matplotlib_panel", "plotly_panel"]),
    ("Bigger builds", ["cad_model3d", "circuit_dashboard", "train_dashboard",
                       "robot_control", "sensor_dashboard", "leaderboard",
                       "hackathon/hackathon"]),
    ("Layout, shapes and the view", ["managed_shapes", "locked_and_arrows",
                                     "layering", "container_layout",
                                     "page_layout", "streamlit_layout",
                                     "fixed_view", "moving_widget"]),
    ("Media and devices", ["webcam_feed", "mic_input", "binary_stream",
                           "remote_control", "arduino_serial/README"]),
    ("Multi-user, sharing and packaging", ["chat_room", "merge_hub",
                                           "public_tunnel", "load_canvas",
                                           "bake_app"]),
]


def summary(path):
    try:
        tree = ast.parse(open(path, encoding="utf-8").read())
    except SyntaxError:
        return None
    doc = ast.get_docstring(tree)
    if not doc:
        return None
    first = doc.strip().splitlines()[0].strip()
    # "Title\n=====" docstrings: the first line is the title
    return first.rstrip(".").rstrip(":")


def main():
    scripts = sorted(f[:-3] for f in os.listdir(EX)
                     if f.endswith(".py") and not f.startswith("test"))
    placed = set()
    lines = ["# Examples", "",
             "Every script is self-contained: `python examples/<name>.py` opens a "
             "browser tab on the canvas it builds. Summaries are each script's "
             "docstring; this file is generated by `scripts/gen_examples_index.py`.",
             ""]
    missing = []

    def row(name):
        rel = name + ".py"
        path = os.path.join(EX, rel)
        if not os.path.isfile(path):
            return None
        s = summary(path)
        if s is None:
            missing.append(rel)
            s = ""
        return f"- [`{rel}`]({rel}) — {s}"

    for title, names in GROUPS:
        rows = []
        for n in names:
            if n.endswith("/README"):
                d = n.split("/")[0]
                if os.path.isdir(os.path.join(EX, d)):
                    rows.append(f"- [`{d}/`]({d}/) — folder example")
                continue
            r = row(n)
            if r:
                rows.append(r)
                placed.add(n)
        if rows:
            lines += [f"## {title}", ""] + rows + [""]
    rest = [row(n) for n in scripts if n not in placed]
    rest = [r for r in rest if r]
    if rest:
        lines += ["## More", ""] + rest + [""]
    lines += ["Notebooks: `merge_canvases.ipynb`, `notebook_autopanel.ipynb`, "
              "`notebook_dynamic.ipynb` — the same API from Jupyter.", ""]
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(lines))
    print(f"wrote {os.path.relpath(OUT, ROOT)} ({len(placed) + len(rest)} scripts)")
    if missing:
        print("no docstring:", ", ".join(missing), file=sys.stderr)


if __name__ == "__main__":
    main()
