"""Download: a button that sends a file (or generated bytes) to the viewer.

The package's usual split applies: the browser can't read the host disk —
Python can — so Python decides exactly *what* bytes leave the machine and the
browser only ever receives an unguessable, short-lived URL pointing at them.
Unlike :class:`~danvas.FileBrowser` (where the *viewer* picks a path, so it
must be sandboxed), here the *host code* names the content, so no path the viewer
sends is ever trusted.

On click the panel asks Python for a download (``canvas.request``); the handler
resolves the current content, stashes it under a one-off token in the bridge, and
returns the ``/__download__/<token>`` URL the server streams it from (behind the
same auth gate as the rest of the canvas). The token expires shortly after, so a
shared/tunneled link can't be replayed indefinitely.

Rendered as a native React panel (like :class:`~danvas.Button`), so it follows
the canvas theme and needs no ``npm`` build.

    # a static file
    canvas.download("report", source="out/report.pdf", text="Download report")

    # content generated fresh on each click
    dl = canvas.download("export", text="Export CSV")

    @dl.provide
    def _():
        return ("data.csv", make_csv().encode())   # (filename, bytes)
"""

import os

from .react import React

# Scoped under `.pc-download`; colours follow the canvas theme with safe
# fallbacks, matching Button so the two read as a family.
_DOWNLOAD_CSS = """
.pc-download{box-sizing:border-box;width:100%;height:100%;padding:8px 12px;
 display:flex;align-items:center;justify-content:center;gap:8px;
 font:600 13px system-ui,-apple-system,sans-serif;color:var(--pc-text,#e6edf3);
 background:var(--pc-surface,#1b2230);border:1px solid var(--pc-border,#30363d);
 border-radius:8px;cursor:pointer;transition:background .12s}
.pc-download:hover{background:var(--pc-surface-hover,#232c3d)}
.pc-download:active{transform:translateY(1px)}
.pc-download:disabled{opacity:.6;cursor:default}
.pc-download-ico{font-size:15px;line-height:1}
"""

# Click -> ask Python for a fresh download URL (content is resolved server-side
# at click time), then trigger a native browser download via a transient <a>.
# ``props.text`` is the face (replayed on reconnect). A short "busy" state keeps
# double-clicks from racing while Python prepares the file.
_DOWNLOAD_SOURCE = """
function Component({ canvas, props }) {
  const [busy, setBusy] = React.useState(false);
  async function go() {
    if (busy) return;
    setBusy(true);
    try {
      const r = await canvas.request({});
      if (r && r.url) {
        const a = document.createElement("a");
        a.href = r.url;
        if (r.filename) a.download = r.filename;
        document.body.appendChild(a);
        a.click();
        a.remove();
      }
    } catch (e) {
      console.error("danvas download failed:", e);
    } finally {
      setBusy(false);
    }
  }
  return (
    <>
      <style>{`__CSS__`}</style>
      <button className="pc-download" disabled={busy} onClick={go}>
        <span className="pc-download-ico">{"\\u2913"}</span>
        {busy ? "Preparing\\u2026" : props.text}
      </button>
    </>
  );
}
""".replace("__CSS__", _DOWNLOAD_CSS)


class Download(React):
    """A button that downloads a host file (or generated bytes) to the viewer.

    Point it at a static ``source`` (a filesystem path or ``bytes``), or leave
    ``source`` unset and register a provider with :meth:`provide` to produce the
    content fresh on every click (an exported CSV, a rendered report). The saved
    filename is, in order of precedence: a ``(filename, data)`` pair returned by
    the provider, the ``filename`` argument, a path's basename, else the panel
    name.

    The host code chooses exactly what each click serves, so — unlike
    :class:`~danvas.FileBrowser` — nothing the viewer sends selects a path.
    """

    default_w = 200
    default_h = 84

    def __init__(self, name="download", source=None, filename=None, text=None, label=None,
                 color=None):
        # ``text`` is the button face; defaults to the label/name so naming the
        # download is enough to caption it.
        caption = text if text is not None else (label if label is not None else name)
        super().__init__(source=_DOWNLOAD_SOURCE, name=name, label=label,
                         props={"text": caption})
        self._init_color(color)
        # The static content to serve (path or bytes); ``None`` when a provider
        # supplies it. Named ``_content`` to avoid colliding with React's
        # ``_source`` (the JSX). ``_filename`` is the saved-as name override.
        self._content = source
        self._filename = filename
        self._provider = None
        # One inbound action: a click asks Python to mint a download URL.
        self.on_request()(self._on_download)

    def provide(self, fn):
        """Decorator: register a callback that returns the content per click.

        The callback takes no arguments and returns the content to send: a
        filesystem path, ``bytes``, or a ``(filename, path_or_bytes)`` pair to
        also set the saved name. Registering a provider supersedes any static
        ``source``. Raising inside it surfaces as a failed download in the
        browser (the button simply re-enables).
        """
        self._provider = fn
        return fn

    def set_source(self, source, filename=None):
        """Replace the static content served on click (path or ``bytes``), live.

        ``filename`` optionally updates the saved-as name. Has no effect while a
        :meth:`provide` callback is registered (the provider wins).
        """
        self._content = source
        if filename is not None:
            self._filename = filename

    def _resolve(self):
        """Resolve the current content to ``(filename, payload)`` for the bridge.

        ``payload`` is either ``bytes`` (served inline) or a filesystem path
        string (streamed by the server). Raises if there's nothing to serve, the
        provider returns a malformed value, or a path doesn't exist — each
        surfaces as a rejected request the panel logs and recovers from.
        """
        result = self._provider() if self._provider is not None else self._content
        if result is None:
            raise ValueError(
                f"download {self.name!r} has nothing to serve — pass source= "
                "or register a @download.provide callback"
            )
        filename = self._filename
        # A (filename, data) pair lets a provider name the file per click.
        if isinstance(result, tuple):
            if len(result) != 2:
                raise ValueError(
                    "a download provider must return a path, bytes, or a "
                    "(filename, data) pair"
                )
            name, result = result
            if name:
                filename = name
        if isinstance(result, (bytes, bytearray, memoryview)):
            return (filename or self.name), bytes(result)
        # Otherwise treat it as a filesystem path.
        path = os.fspath(result)
        if not os.path.isfile(path):
            raise FileNotFoundError(f"download {self.name!r}: no such file: {path}")
        return (filename or os.path.basename(path) or self.name), path

    def _on_download(self, _req):
        """Answer a click: stash the resolved content and return its URL."""
        if self._bridge is None:
            raise RuntimeError("download is not attached to a serving canvas")
        filename, payload = self._resolve()
        token = self._bridge.register_download(filename, payload)
        return {"url": f"/__download__/{token}", "filename": filename}